//! Embedded Whisper model bytes.
//!
//! Whisper embed is **opt-in** (`CODESCRIBE_EMBED_WHISPER=1`) for fat/offline
//! SKUs only. The daily public build leaves this payload empty and resolves
//! Whisper at runtime (HF cache, `~/.codescribe/models`, Settings download).

/// Whisper bytes generated by `build.rs` when `CODESCRIBE_EMBED_WHISPER=1`.
#[cfg(embed_model)]
mod data {
    include!(concat!(env!("OUT_DIR"), "/embedded_model_data.rs"));
}

/// Empty stand-ins for the daily build, which resolves Whisper at runtime.
#[cfg(not(embed_model))]
mod data {
    /// Empty `config.json` stand-in when Whisper is not build-time embedded.
    pub static CONFIG: &[u8] = &[];
    /// Empty tokenizer stand-in for the daily (non-fat) build.
    pub static TOKENIZER: &[u8] = &[];
    /// Empty mel filterbank stand-in for the daily (non-fat) build.
    pub static MEL_FILTERS: &[u8] = &[];
    /// Empty weights stand-in; runtime resolves models from disk/HF instead.
    pub static WEIGHTS: &[u8] = &[];
}

/// Check if optional embedded model bytes are available.
pub fn is_embedded_available() -> bool {
    let weights_size = data::WEIGHTS.len();
    tracing::debug!(weights_size, "Embedded model check");
    weights_size > 0
}

/// Get optional embedded model data if available.
pub fn get_embedded_data() -> Option<EmbeddedModel> {
    if !is_embedded_available() {
        return None;
    }
    Some(EmbeddedModel {
        config: data::CONFIG,
        tokenizer: data::TOKENIZER,
        mel_filters: data::MEL_FILTERS,
        weights: data::WEIGHTS,
    })
}

/// Embedded model data - static byte slices from binary.
pub struct EmbeddedModel {
    /// Model configuration (`config.json`).
    pub config: &'static [u8],
    /// Tokenizer (`tokenizer.json`).
    pub tokenizer: &'static [u8],
    /// Precomputed mel filterbank used by the feature extractor.
    pub mel_filters: &'static [u8],
    /// Model weights (`model.safetensors`).
    pub weights: &'static [u8],
}

impl EmbeddedModel {
    /// Total size in bytes
    pub fn total_size(&self) -> usize {
        self.config.len() + self.tokenizer.len() + self.mel_filters.len() + self.weights.len()
    }
}

/// Compile-flag gates for present vs absent embedded Whisper payloads.
#[cfg(test)]
mod tests {
    use super::*;

    /// Fat builds (`embed_model`) must ship non-empty config/tokenizer/weights.
    #[test]
    #[cfg(embed_model)]
    fn embedded_payload_is_available_when_compiled_in() {
        assert!(is_embedded_available());
        let model = get_embedded_data().expect("embedded payload must exist");
        assert!(!model.config.is_empty());
        assert!(!model.tokenizer.is_empty());
        assert!(!model.mel_filters.is_empty());
        assert!(!model.weights.is_empty());
        assert!(model.total_size() > 0);
    }

    /// Daily builds leave the payload empty so `get_embedded_data` is None.
    #[test]
    #[cfg(not(embed_model))]
    fn embedded_payload_is_absent_when_not_compiled_in() {
        assert!(!is_embedded_available());
        assert!(get_embedded_data().is_none());
    }
}
