#!/bin/bash
# Codescribe — Mac App Store (MAS) readiness preflight
#
# READ-ONLY. Inspects the repo for state that is known-incompatible with Mac App
# Store distribution and reports each item as a blocker (P0), a warning (P1), or
# OK. It does NOT modify build behavior, entitlements, or any tracked file.
#
# The current shipping lane is Developer ID + notarization (outside the App
# Store). This script does not change that. It exists so an operator can answer
# "how far is the tree from a sandbox-clean MAS build?" without re-deriving it by
# hand. See docs/APP_STORE_READINESS.md for the full plan and citations.
#
# Usage:
#   ./scripts/appstore-preflight.sh          # human-readable report
#   ./scripts/appstore-preflight.sh && echo OK   # exit 0 only if no P0 blockers
#
# Exit code: 0 = no P0 blockers found, 1 = at least one P0 blocker.
#
# Created by Vetcoders (c)2026

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(dirname "$SCRIPT_DIR")"
cd "$ROOT"

ENTITLEMENTS="scripts/entitlements.plist"
BASIC_ENTITLEMENTS="scripts/entitlements.appstore-basic.plist"
MAKEFILE="Makefile"
KEYCHAIN_RS="core/config/keychain.rs"
RELEASE_YML=".github/workflows/release.yml"
# The SwiftUI app's Info.plist is generated by xcodegen from macos/project.yml
# (info.properties), and the privacy manifest ships from macos/Codescribe/ —
# these are the live surfaces since the AppKit excision.
PROJECT_YML="macos/project.yml"
PRIVACY_MANIFEST="macos/Codescribe/PrivacyInfo.xcprivacy"

P0=0
P1=0

red()   { printf '\033[31m%s\033[0m\n' "$1"; }
green() { printf '\033[32m%s\033[0m\n' "$1"; }
yellow(){ printf '\033[33m%s\033[0m\n' "$1"; }

blocker() { red   "  [P0] $1"; P0=$((P0 + 1)); }
warn()    { yellow "  [P1] $1"; P1=$((P1 + 1)); }
ok()      { green "  [OK] $1"; }

echo "═══════════════════════════════════════════════════════════"
echo "  Codescribe — Mac App Store readiness preflight (read-only)"
echo "═══════════════════════════════════════════════════════════"

# 1. App Sandbox — REQUIRED for MAS, intentionally enabled only for Basic.
echo ""
echo "▶ App Sandbox entitlement (com.apple.security.app-sandbox)"
if ! grep -q "^  CodescribeBasic:" "$PROJECT_YML" 2>/dev/null; then
    blocker "No CodescribeBasic target in $PROJECT_YML. MAS needs a separate sandboxed Basic SKU, not the Pro target."
elif ! grep -q "PRODUCT_BUNDLE_IDENTIFIER: com.vetcoders.codescribe.basic" "$PROJECT_YML" 2>/dev/null; then
    blocker "CodescribeBasic does not use the distinct MAS bundle id com.vetcoders.codescribe.basic."
elif ! grep -q "CODE_SIGN_ENTITLEMENTS: .*scripts/entitlements.appstore-basic.plist" "$PROJECT_YML" 2>/dev/null; then
    blocker "CodescribeBasic is not wired to $BASIC_ENTITLEMENTS via CODE_SIGN_ENTITLEMENTS."
elif [ ! -f "$BASIC_ENTITLEMENTS" ]; then
    blocker "Missing $BASIC_ENTITLEMENTS for the sandboxed Basic SKU."
elif command -v plutil >/dev/null 2>&1 && ! plutil -lint "$BASIC_ENTITLEMENTS" >/dev/null 2>&1; then
    blocker "$BASIC_ENTITLEMENTS is not a valid plist (plutil -lint failed)."
elif grep -q "com.apple.security.app-sandbox" "$BASIC_ENTITLEMENTS" 2>/dev/null \
   && grep -A1 "com.apple.security.app-sandbox" "$BASIC_ENTITLEMENTS" | grep -q "<true/>"; then
    ok "CodescribeBasic has App Sandbox enabled via $BASIC_ENTITLEMENTS; Pro remains on Developer ID entitlements."
else
    blocker "App Sandbox is NOT enabled in $BASIC_ENTITLEMENTS. MAS rejects builds without it."
fi

# 2. Hardened-runtime relaxations that conflict with a clean sandboxed MAS build.
echo ""
echo "▶ Sandbox-hostile hardened-runtime relaxations"
for key in \
    "com.apple.security.cs.disable-library-validation" \
    "com.apple.security.cs.allow-unsigned-executable-memory" \
    "com.apple.security.cs.allow-dyld-environment-variables"; do
    if grep -q "$key" "$ENTITLEMENTS" 2>/dev/null; then
        warn "$key present (required by embedded ML dylibs; review against MAS — see readiness doc)."
    else
        ok "$key absent."
    fi
done

# 3. Privacy manifest — required by App Store Connect since 2024-05-01.
#    The live manifest is $PRIVACY_MANIFEST, wired into the bundle's resources
#    build phase via $PROJECT_YML (a stray template elsewhere does not count).
echo ""
echo "▶ Privacy manifest (PrivacyInfo.xcprivacy)"
if [ ! -f "$PRIVACY_MANIFEST" ]; then
    blocker "No $PRIVACY_MANIFEST. Required-reason APIs (FileTimestamp via std::fs metadata) are used; MAS submission needs it."
elif ! grep -q "PrivacyInfo.xcprivacy" "$PROJECT_YML" 2>/dev/null; then
    blocker "$PRIVACY_MANIFEST exists but is not referenced by $PROJECT_YML — xcodebuild will not copy it into the bundle."
elif command -v plutil >/dev/null 2>&1 && ! plutil -lint "$PRIVACY_MANIFEST" >/dev/null 2>&1; then
    blocker "$PRIVACY_MANIFEST is not a valid plist (plutil -lint failed)."
else
    ok "PrivacyInfo.xcprivacy present, wired into $PROJECT_YML, and lints as a plist."
fi

# 4. Bundle identifier consistency across the surfaces that must agree.
echo ""
echo "▶ Bundle identifier consistency"
MK_ID="$(grep -E "^CODESCRIBE_BUNDLE_ID \?=" "$MAKEFILE" 2>/dev/null | sed -E 's/.*= *//' | tr -d ' ')"
KC_ID="$(grep -oE "com\.[a-zA-Z0-9.]+codescribe[a-zA-Z0-9.]*" "$KEYCHAIN_RS" 2>/dev/null | head -1)"
YML_ID="$(grep -oE "com\.[a-zA-Z0-9.]+codescribe[a-zA-Z0-9.]*|com\.codescribe\.app" "$RELEASE_YML" 2>/dev/null | head -1)"
echo "    Makefile default : ${MK_ID:-<none>}"
echo "    keychain.rs      : ${KC_ID:-<none>}"
echo "    release.yml      : ${YML_ID:-<none>}"
if [ -n "$MK_ID" ] && [ "$MK_ID" = "$KC_ID" ] && [ "$MK_ID" = "$YML_ID" ]; then
    ok "Bundle id is consistent across Makefile, keychain, and release workflow."
else
    warn "Bundle id differs across surfaces. A MAS app record needs one canonical id (TCC + keychain identity)."
fi

# 5. Apple Events / Accessibility purpose strings — MAS review risk under sandbox.
#    Info.plist is generated by xcodegen from $PROJECT_YML info.properties (the
#    old Makefile bundle target is a dead surface since the AppKit excision).
echo ""
echo "▶ Sandbox-review-sensitive purpose strings ($PROJECT_YML info.properties)"
if grep -q "NSAppleEventsUsageDescription" "$PROJECT_YML" 2>/dev/null; then
    warn "NSAppleEventsUsageDescription present. Apple-events temporary exception is 'most often rejected' by App Review."
else
    ok "No NSAppleEventsUsageDescription."
fi
if grep -q "NSAccessibilityUsageDescription" "$PROJECT_YML" 2>/dev/null; then
    warn "NSAccessibilityUsageDescription present. Accessibility for non-accessibility purposes risks Guideline 2.4.5 rejection."
else
    ok "No NSAccessibilityUsageDescription."
fi

# 6. App Store distribution path — none today (Developer ID only).
echo ""
echo "▶ App Store upload path"
if grep -qiE "productbuild|App Store Connect|altool|Transporter|3rd Party Mac Developer|Apple Distribution" "$MAKEFILE" "$RELEASE_YML" 2>/dev/null; then
    ok "An App Store distribution path is referenced."
else
    blocker "No App Store distribution path (productbuild/pkg, Apple Distribution cert, App Store Connect upload). Only Developer ID + notarization exists."
fi

# 7. Basic-SKU draft scaffolding — informational (does not affect exit code).
echo ""
echo "▶ Basic SKU draft scaffolding (informational)"
if [ -f "scripts/entitlements.appstore-basic.plist" ]; then
    ok "Draft sandbox entitlements present (scripts/entitlements.appstore-basic.plist)."
else
    yellow "  [info] No draft sandbox entitlements (scripts/entitlements.appstore-basic.plist)."
fi
if [ -f "scripts/PrivacyInfo.xcprivacy.template" ]; then
    ok "Draft privacy manifest present (scripts/PrivacyInfo.xcprivacy.template)."
else
    yellow "  [info] No draft privacy manifest template."
fi

echo ""
echo "───────────────────────────────────────────────────────────"
echo "  Summary: $P0 P0 blocker(s), $P1 P1 warning(s)"
echo "  Lane today: Developer ID + notarization (outside App Store)."
echo "  Full plan + Apple citations: docs/APP_STORE_READINESS.md"
echo "───────────────────────────────────────────────────────────"

if [ "$P0" -gt 0 ]; then
    exit 1
fi
exit 0
